name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOURCE_PATH: "${{ github.workspace }}/cpp-client-reference"
  VCPKG_ARCHIVE_PATH: "${{ env.SOURCE_PATH }}/vcpkg_archives"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        preset:
          - x64-windows-msvc-release
          - x64-linux-gcc-release
          - x64-linux-clang-release
        include:
          - os: windows-latest
            preset: x64-windows-msvc-release
            build_type: Release
          - os: ubuntu-latest
            preset: x64-linux-gcc-release
            build_type: Release
          - os: ubuntu-latest
            preset: x64-linux-clang-release
            build_type: Release

    env:
      VCPKG_BINARY_SOURCES: "files,$VCPKG_ARCHIVE_PATH,readwrite"

    steps:
    - name: List environment variables
      run: env

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Vcpkg archives
      id: cache-vcpkg-archives
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}
        path: "$VCPKG_ARCHIVE_PATH"

    - name: Configure CMake
      run: >
        cmake
        -S "$SOURCE_PATH"
        -B "$SOURCE_PATH/out"
        --preset=${{ matrix.preset }}

    - name: Build
      # Note: --config is needed for multi-config generators such as the Visual Studio ones.
      run: cmake --build "$SOURCE_PATH/out" --config ${{ matrix.build_type }}
