name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        preset:
          - x64-windows-msvc-release
          - x64-linux-gcc-release
          - x64-linux-clang-release
        include:
          - os: windows-latest
            preset: x64-windows-msvc-release
            build_type: Release
          - os: ubuntu-latest
            preset: x64-linux-gcc-release
            build_type: Release
          - os: ubuntu-latest
            preset: x64-linux-clang-release
            build_type: Release

    steps:
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        SOURCE_PATH="${{ github.workspace }}/cpp-client-reference";
        VCPKG_ARCHIVE_PATH="$SOURCE_PATH/vcpkg_archives";
        echo "source-path=$SOURCE_PATH" >> "$GITHUB_OUTPUT";
        echo "vcpkg-archive-path=$VCPKG_ARCHIVE_PATH" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: echo "VCPKG_BINARY_SOURCES=files,${{ steps.strings.outputs.vcpkg-archive-path }},readwrite" >> "$GITHUB_ENV"

    - name: List environment variables
      run: env

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Vcpkg archives
      id: cache-vcpkg-archives
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}
        path: "${{ steps.strings.outputs.vcpkg-archive-path }}"

    - name: Configure CMake
      run: >
        cmake
        -S "${{ steps.strings.outputs.source-path }}"
        -B "${{ steps.strings.outputs.source-path }}/out"
        --preset=${{ matrix.preset }}

    - name: Build
      # Note: --config is needed for multi-config generators such as the Visual Studio ones.
      run: cmake --build "${{ steps.strings.outputs.source-path }}/out" --config ${{ matrix.build_type }}
