# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable("projectFile", "csharp-client-reference/csharp-client-reference.csproj")

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore "${{ env.projectFile }}"
    - name: Build
      run: dotnet build --no-restore "${{ env.projectFile }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal "${{ env.projectFile }}"
