
# from https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml
name: Gradle assemble & test
env:
  JAVA_VERSION: "17"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: { java-version: "${{ env.JAVA_VERSION }}", distribution: 'zulu' }

      - { name: Setup, uses: gradle/actions/setup-gradle@v4 }
      - { name: Test, run: ./gradlew test }

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with: { report_paths: '**/build/test-results/test/TEST-*.xml' }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

  assemble:
    runs-on: ubuntu-latest
    permissions: { contents: read, checks: write }

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: { java-version: "${{ env.JAVA_VERSION }}", distribution: 'zulu' }

      - { name: Setup, uses: gradle/actions/setup-gradle@v4 }
      - { name: Clean, run: ./gradlew clean }
      - name: Build
        run: ./gradlew assemble
        env: { VOLITION_BUILD_NUMBER: "${{ github.run_number }}" }

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          # the point of artifacts is to pass between workflows,
          # so they're averse to having specific (ie versioned) names.
          # bummer, but github artifacts is not an artifact server.
          name: "volition-api-libs"
          path: api/build/libs